Revert "Support -sh scripts"
This reverts commit 6e08d4b1bed4001ff61e9a999ad53665cdc8d720.

diff --git a/simplesub b/simplesub
--- a/simplesub
+++ b/simplesub
@@ -40,14 +40,8 @@ main () {
                 fi
             fi
 
-            sh_command_path="$(command -v "$scriptname-sh-$command")" || :
-            if [ -n "$sh_command_path" ]; then
-                # shellcheck disable=SC1090
-                . "$sh_command_path" "$@"
-            else
-                command_path="$(command -v "$scriptname-$command")" || die "command not found: $scriptname-$command"
-                exec "$command_path" "$@"
-            fi
+            command_path="$(command -v "$scriptname-$command")" || die "command not found: $scriptname-$command"
+            exec "$command_path" "$@"
             ;;
     esac
 }
