Support -sh scripts
Signed-off-by: Christopher Larson <chris_larson@mentor.com>

diff --git a/simplesub b/simplesub
--- a/simplesub
+++ b/simplesub
@@ -37,8 +37,14 @@ main () {
                 fi
             fi
 
-            command_path="$(command -v "$scriptname-$command")" || die "command not found: $scriptname-$command"
-            exec "$command_path" "$@"
+            sh_command_path="$(command -v "$scriptname-sh-$command")" || :
+            if [ -n "$sh_command_path" ]; then
+                # shellcheck disable=SC1090
+                . "$sh_command_path" "$@"
+            else
+                command_path="$(command -v "$scriptname-$command")" || die "command not found: $scriptname-$command"
+                exec "$command_path" "$@"
+            fi
             ;;
     esac
 }
